// Minimal ABIs the agent needs. Generated by hand to avoid a build-step dependency
// on forge inspect. Regenerate if contract signatures change.

export const proposalFactoryAbi = [
  {
    type: "event",
    name: "ProposalCreated",
    inputs: [
      { name: "proposalId", type: "uint256", indexed: true },
      { name: "proposer", type: "address", indexed: true },
      { name: "passConditionId", type: "bytes32", indexed: false },
      { name: "failConditionId", type: "bytes32", indexed: false },
      { name: "passAMM", type: "address", indexed: false },
      { name: "failAMM", type: "address", indexed: false },
      { name: "tradingDeadline", type: "uint256", indexed: false },
      { name: "kpiObservationBlock", type: "uint256", indexed: false },
    ],
  },
  {
    type: "function",
    name: "getProposal",
    stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [
      { name: "proposer", type: "address" },
      { name: "passAMM", type: "address" },
      { name: "failAMM", type: "address" },
      { name: "passConditionId", type: "bytes32" },
      { name: "failConditionId", type: "bytes32" },
      { name: "tradingDeadline", type: "uint256" },
      { name: "kpiObservationBlock", type: "uint256" },
      { name: "kpiLo", type: "uint256" },
      { name: "kpiHi", type: "uint256" },
      { name: "state", type: "uint8" },
    ],
  },
  {
    type: "function",
    name: "getExecutionPayload",
    stateMutability: "view",
    inputs: [{ name: "proposalId", type: "uint256" }],
    outputs: [
      { name: "targets", type: "address[]" },
      { name: "values", type: "uint256[]" },
      { name: "calldatas", type: "bytes[]" },
      { name: "salt", type: "bytes32" },
    ],
  },
] as const;

export const futarchyAmmAbi = [
  {
    type: "function",
    name: "getLongPrice",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "getReserves",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "rColl", type: "uint112" },
      { name: "rLong", type: "uint112" },
      { name: "ts", type: "uint32" },
    ],
  },
  {
    type: "function",
    name: "longToken",
    stateMutability: "view",
    inputs: [],
    outputs: [{ type: "address" }],
  },
  {
    type: "function",
    name: "swapCollateralForLong",
    stateMutability: "nonpayable",
    inputs: [
      { name: "collateralIn", type: "uint256" },
      { name: "minLongOut", type: "uint256" },
      { name: "to", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "swapLongForCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "longIn", type: "uint256" },
      { name: "minCollateralOut", type: "uint256" },
      { name: "to", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
] as const;

export const erc20Abi = [
  {
    type: "function",
    name: "approve",
    stateMutability: "nonpayable",
    inputs: [
      { name: "spender", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [{ type: "bool" }],
  },
  {
    type: "function",
    name: "balanceOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "allowance",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "spender", type: "address" },
    ],
    outputs: [{ type: "uint256" }],
  },
] as const;
